name: Build and test

on:
  pull_request:
    branches: ["main", "dev**"]
  workflow_dispatch:

env:
  CONFIGURATION: Debug
  DOTNET_VERSION: 7.0.x
  PROJECT_DIRECTORY: Src

concurrency:
  group: build

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Restore dependencies
        run: dotnet restore "${{ env.PROJECT_DIRECTORY }}"

      - name: Build
        run: dotnet build "${{ env.PROJECT_DIRECTORY }}" --configuration ${{ env.CONFIGURATION }} --no-restore

      - name: Test
        run: dotnet test "${{ env.PROJECT_DIRECTORY }}" --no-build
